language: java

sudo: required

jdk:
  - oraclejdk8
  
services:
  - docker

script:
  - mvn clean package docker:build
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag parking-api gustajz/parking-api
  - docker push gustajz/parking-api

cache:
  directories:
    - $HOME/.m2