language: java

addons:
  apt:
    packages:
    - xml2

sudo: required

jdk:
  - oraclejdk8
  
services:
  - docker

script:
  - mvn clean package docker:build

#branches:
#  only:
#  - master

after_success:
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then ./docker_push.sh; fi
 
cache:
  directories:
    - $HOME/.m2