language: java

addons:
  apt:
    packages:
    - xml2

sudo: required

jdk:
  - oraclejdk8
  
services:
  - docker

script:
  - mvn clean package docker:build

branches:
  only:
  - master
  - develop

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then 
        source docker_push.sh; 
    else 
        source docker_push_snapshot.sh; 
    fi

cache:
  directories:
    - $HOME/.m2
