server:
  contextPath: /api
  session:
    timeout: 60

spring:
  datasource:
    continue-on-error: true
    driver-class-name: org.postgresql.Driver
    tomcat: 
      maxActive: 10
      initialSize: 4
      maxIdle: 8
      minIdle: 4
      testOnBorrow: true
      testOnConnect: true
      validationQuery: SELECT 1
      initSQL: SELECT 1
      jdbcInterceptors: ConnectionState;StatementFinalizer;ResetAbandonedTimer    
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  
  jpa:
    hibernate:
      ddl-auto: none

ldap:
  url: ${LDAP_URL}
  domain: ${LDAP_DOMAIN}

liquibase:
  change-log: classpath:/db/changelog-master.xml

---
spring:
  profiles: development

  datasource:
    url: jdbc:postgresql://localhost:5432/parking
    username: parking
    password: parking

ldap:
  url: ldap://s005.cwinet.local
  domain: cwinet.local
  
logging: 
  level:
    parking: trace
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
